Repository codelancedevs/Sundar-Clinic, pull requests merged in 2022-02, with the labels that each got.

#14 Tested Updates - Patient and Admin
  api/app/admin/controller.js
  api/app/admin/routes.js
  api/app/mail/controller.js
  api/app/mail/index.js
  api/app/mail/model.js
  api/app/mail/routes.js
  api/app/patient/model.js
  api/app/src/controller.js
  api/app/src/model.js
  api/app/user/controller.js
  api/app/user/model.js
  api/app/user/routes.js
  api/helper/config/index.js
  api/helper/database/index.js
  api/helper/functions/index.js
  api/helper/mail/templates/index.js
  api/helper/mail/templates/resendVerify.js
  api/helper/mail/templates/resetPassword.js
  api/helper/mail/templates/verifyAdmin.js
  api/helper/mail/templates/verifyPatient.js
  api/helper/middleware/index.js
  package-lock.json
  package.json
  server.js
  test.js
Labels: enhancement

#15 Issue Fix for React App URL for CORS
  api/app/admin/controller.js
  api/app/patient/controller.js
  api/helper/config/index.js
  api/helper/database/index.js
  server.js
Labels: bug

#16 Patient Features Added
  .env.sample
  api/app/admin/controller.js
  api/app/admin/index.js
  api/app/admin/model.js
  api/app/admin/routes.js
  api/app/patient/controller.js
  api/app/patient/index.js
  api/app/patient/model.js
  api/app/patient/routes.js
  api/app/posts/controller.js
  api/app/posts/index.js
  api/app/posts/model.js
  api/app/posts/routes.js
  api/app/src/controller.js
  api/app/src/index.js
  api/app/src/model.js
  api/app/src/routes.js
  api/app/user/controller.js
  api/app/user/index.js
  api/app/user/model.js
  api/app/user/routes.js
  api/helper/config/index.js
  api/helper/database/index.js
  api/helper/functions/index.js
  api/helper/mail/index.js
  api/helper/mail/templates/index.js
  api/helper/middleware/index.js
  package-lock.json
  package.json
  server.js
Labels: enhancement

#21 Patient Account, General, Password and Presenting Complaint Routes made and tested
  api/app/admin/controller.js
  api/app/admin/routes.js
  api/app/patient/controller.js
  api/app/patient/model.js
  api/app/patient/routes.js
  package.json
Labels: enhancement

#23 Admin and Patient Major Features Implemented
  api/app/admin/controller.js
  api/app/admin/routes.js
  api/app/posts/model.js
  package.json
Labels: enhancement

#24 Posts CRUD added and tested
  api/app/posts/controller.js
  api/app/posts/model.js
  api/app/posts/routes.js
  package.json
Labels: enhancement

#28 Update on Almost Stable Fix
  LICENSE
  api/app/src/controller.js
  api/app/src/model.js
  api/app/src/routes.js
  api/helper/middleware/index.js
  package.json
  server.js
Labels: enhancement

#31 Added MongoDB Id verification for required routes
  api/app/admin/controller.js
  api/app/patient/controller.js
  api/app/posts/controller.js
  api/app/src/controller.js
  package-lock.json
Labels: bug

#32 Version Update
  package.json
Labels: documentation

#35 v0.6.0 Major Admin Patient CRUD features related to Presenting Complaint and History
  api/app/admin/controller.js
  api/app/admin/routes.js
  api/app/patient/controller.js
  api/app/patient/model.js
  api/app/patient/routes.js
  package-lock.json
  package.json
Labels: enhancement

#43 Added Redux for Snackbar and Backdrop
  package-lock.json
  package.json
  prettier.config.js
  src/App.js
  src/components/Navbar/index.jsx
  src/components/Reusable/BackdropComponent.jsx
  src/components/Reusable/SnackbarComponent.jsx
  src/config/routes.js
  src/functions/server.js
  src/pages/About.jsx
  src/pages/Contact.jsx
  src/pages/Email/ResetPassword.jsx
  src/pages/Email/VerifyAccount.jsx
  src/pages/Gallery.jsx
  src/pages/Home.jsx
  src/pages/NotFound.jsx
  src/pages/Posts.jsx
  src/pages/PrivacyPolicy.jsx
  src/pages/TermsOfService.jsx
  src/routes/index.jsx
  src/store/features/app.js
  src/store/features/test.js
  src/store/features/user.js
  src/store/index.js
Labels: enhancement

#44 Netlify setup
  public/_redirects
  src/App.js
  src/store/features/app.js
Labels: bug

#49 Testing Email with new Images
  package-lock.json
  package.json
  public/assets/logo/logoSmallTransparent.png
  src/api/patient/controller.js
  src/helper/mail/index.js
  views/email/components/commonCss.ejs
  views/email/welcomeAndVerify.ejs
Labels: enhancement

#52 Stable Release Ready
  package-lock.json
  package.json
  postcss.config.js
  public/assets/post/Job.gif
  server.js
  src/api/admin/controller.js
  src/api/admin/model.js
  src/api/app/controller.js
  src/api/patient/controller.js
  src/api/patient/model.js
  src/api/posts/controller.js
  src/api/posts/model.js
  src/api/user/controller.js
  src/api/user/model.js
  src/helper/functions/index.js
  src/helper/mail/functions.js
  src/helper/mail/index.js
  src/helper/mail/templates/index.js
  src/helper/mail/templates/resetPassword.js
  src/helper/mail/templates/verify.js
  src/helper/mail/templates/welcome.js
  src/helper/middleware/index.js
  src/temp/tailwind.css
  tailwind.config.js
  views/email/components/commonCss.ejs
  views/email/components/footer.ejs
  views/email/components/header.ejs
  views/email/resetPassword.ejs
  views/email/verifyAccount.ejs
  views/email/welcomeAndVerify.ejs
  views/index.ejs
Labels: documentation, enhancement
